# See: https://github.com/github/super-linter
---
name: Linter
on:
  push:
    branches: [master]
    paths:
      - '**.md'
      - '**.yaml'
      - '**.yml'
  pull_request:
    branches: [master]
    paths:
      - '**.md'
      - '**.yaml'
      - '**.yml'
jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Lint Markdown and YAML files
        uses: docker://github/super-linter:v3.3.0
        env:
          VALIDATE_MD: true
          VALIDATE_YAML: true
